# Generated by Django 2.2.3 on 2019-08-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='dateCreated',
            new_name='date_created',
        ),
    ]
