# Generated by Django 2.2.3 on 2019-08-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20190828_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='date_created',
            field=models.DateField(default='Aug, 28 2019'),
        ),
    ]
