# Generated by Django 2.2.3 on 2019-08-27 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0003_auto_20190828_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 28)),
        ),
    ]
